/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -104.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -90.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -97.2820 -213.0829 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -76.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -83.2820 -213.0829 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -90.2820 -200.9585 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -62.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -213.0829 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -76.2820 -200.9585 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -83.2820 -188.8342 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -48.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -55.2820 -213.0829 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -62.2820 -200.9585 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -188.8342 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -76.2820 -176.7098 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -34.2820 -225.2073 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -41.2820 -213.0829 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -48.2820 -200.9585 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -55.2820 -188.8342 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -62.2820 -176.7098 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -164.5855 0.0000 mm
/gps/pos/radius 3.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -29.2820 -261.9060 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -39.2820 -279.2265 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -49.2820 -261.9060 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -49.2820 -296.5470 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -59.2820 -279.2265 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -261.9060 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -59.2820 -313.8675 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -296.5470 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -79.2820 -279.2265 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -89.2820 -261.9060 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -69.2820 -331.1880 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -79.2820 -313.8675 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -89.2820 -296.5470 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -99.2820 -279.2265 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 2.040816
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -109.2820 -261.9060 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -39.0000 -347.5167 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -13.0000 -347.5167 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -26.0000 -325.0000 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 13.0000 -347.5167 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 0.0000 -325.0000 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -13.0000 -302.4833 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 39.0000 -347.5167 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 26.0000 -325.0000 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 13.0000 -302.4833 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.448980
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -0.0000 -279.9667 0.0000 mm
/gps/pos/radius 6.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 101.2820 -266.5248 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 85.2820 -294.2376 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 69.2820 -266.5248 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 69.2820 -321.9504 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 53.2820 -294.2376 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 5.224490
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 37.2820 -266.5248 0.0000 mm
/gps/pos/radius 8.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 31.2820 -226.9393 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 69.2820 -226.9393 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 50.2820 -194.0303 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 107.2820 -226.9393 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 88.2820 -194.0303 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 7.367347
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 69.2820 -161.1214 0.0000 mm
/gps/pos/radius 9.5000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.877551
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 22.0000 -152.2983 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.877551
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -0.0000 -190.4034 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.877551
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -22.0000 -152.2983 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/run/beamOn 83333333
