# Contrast Phantom: 225Ac dual-energy (218+440 keV)
# Rotate 7/20, phi=108.0 deg
# Whole-run expected yield ratio: 218:440 = 0.114:0.261
# Rods: alternating Fr-218 / Bi-440 to model daughter redistribution
# Fr/Bi spatial maps are normalized separately before yield weighting
# beamOn counts selected primary photons, not 225Ac decays

/gps/particle gamma
/gps/energy 218 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 120.0000 mm
/gps/pos/halfz 15.0000 mm
/gps/pos/centre 0.0000 -245.0000 0.0000 mm
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg

#
/gps/source/add 2.205584572117
/gps/particle gamma
/gps/energy 440 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 120.0000 mm
/gps/pos/halfz 15.0000 mm
/gps/pos/centre 0.0000 -245.0000 0.0000 mm
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg

#
# rod 1: Fr-218 at (-18.5, -302.1), d=10mm, relative weight=0.008680555556
/gps/source/add 0.008680555556
/gps/particle gamma
/gps/energy 218 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -18.5410 -302.0634 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
# rod 2: Bi-440 at (40.1, -289.6), d=14mm, relative weight=0.037525570845
/gps/source/add 0.037525570845
/gps/particle gamma
/gps/energy 440 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 40.1478 -289.5887 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
# rod 3: Fr-218 at (58.7, -232.5), d=18mm, relative weight=0.028125000000
/gps/source/add 0.028125000000
/gps/particle gamma
/gps/energy 218 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 58.6889 -232.5253 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
# rod 4: Bi-440 at (18.5, -187.9), d=22mm, relative weight=0.092665185148
/gps/source/add 0.092665185148
/gps/particle gamma
/gps/energy 440 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 18.5410 -187.9366 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
# rod 5: Fr-218 at (-40.1, -200.4), d=26mm, relative weight=0.058680555556
/gps/source/add 0.058680555556
/gps/particle gamma
/gps/energy 218 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -40.1478 -200.4113 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
# rod 6: Bi-440 at (-58.7, -257.5), d=30mm, relative weight=0.172311294697
/gps/source/add 0.172311294697
/gps/particle gamma
/gps/energy 440 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -58.6889 -257.4747 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/run/beamOn 50000000
