%% GenProj_Hoffman_SPECT_PolarCoor
% Generate Hoffman phantom CntStat data from the polar system matrix.
% The phantom is loaded from the compressed Hoffman volume generated by:
%   Geant4Sim/BrainPhantom_HoffmanRawCompressed_3D.m

clear;
clc;
rng(20260412);

%% User config
energy_keV = 511;
rotate_num = 20;
total_count = 5e10;
count_level = "5e10";
data_file_name = "HoffmanCompressed";
volume_type = "target"; % "target" or "native"
transverse_scale = 1.4;

cntstat_noise_mode = "gaussian"; % "gaussian" or "poisson" or "none"
save_img_cartesian = true;
save_img_polar = true;

%% Factor paths
factor_path = sprintf("./Factors/%dkeV_RotateNum%d/", energy_keV, rotate_num);
cntstat_dir = sprintf("./CntStat/%dkeV_RotateNum%d/", energy_keV, rotate_num);
if ~exist(cntstat_dir, "dir")
    mkdir(cntstat_dir);
end

load(sprintf("%sRotMat.mat", factor_path), "RotMat");
load(sprintf("%scoor_polar_full.mat", factor_path), "coor_polar_full");

fid = fopen(sprintf("%sSysMat_polar", factor_path), "r");
if fid < 0
    error("Failed to open %sSysMat_polar", factor_path);
end
SysMat = fread(fid, "float32");
fclose(fid);
SysMat = reshape(SysMat, [], size(coor_polar_full, 1));
total_count_singleview = total_count / size(RotMat, 2);

%% Load Hoffman phantom volume
[img_cartesian, x_src_mm, y_src_mm, z_src_mm, volume_tag] = load_hoffman_volume(volume_type, transverse_scale);
pixel_num_cartesian_z = numel(z_src_mm);

%% Interpolate from Cartesian Hoffman volume to polar coordinates
[x_src_grid, y_src_grid, z_src_grid] = meshgrid(x_src_mm, y_src_mm, z_src_mm);
img_polar = interp3( ...
    x_src_grid, ...
    y_src_grid, ...
    z_src_grid, ...
    permute(img_cartesian, [2, 1, 3]), ...
    coor_polar_full(:, 1), ...
    coor_polar_full(:, 2), ...
    coor_polar_full(:, 3), ...
    "linear", ...
    0);

img_polar = reshape(img_polar, [], pixel_num_cartesian_z);
img_polar = max(img_polar, 0);
if sum(img_polar, "all") <= 0
    error("Interpolated Hoffman phantom is empty on the polar grid.");
end
img_polar = img_polar * total_count_singleview / sum(img_polar, "all");

%% Generate CntStat from system matrix
CntStat = zeros(rotate_num, size(SysMat, 1), "single");
for id_rotate = 1:rotate_num
    RotMat_tmp = RotMat(:, id_rotate);
    img_tmp = reshape(img_polar(RotMat_tmp, :), [], 1);
    cnt_expect = (SysMat * img_tmp).';

    switch lower(cntstat_noise_mode)
        case "gaussian"
            for i = 1:length(cnt_expect)
                sigma = sqrt(max(cnt_expect(i), 0));
                tmp_count = normrnd(cnt_expect(i), sigma);
                cnt_expect(i) = max(0, round(tmp_count));
            end
        case "poisson"
            cnt_expect = poissrnd(max(cnt_expect, 0));
        case "none"
            cnt_expect = max(0, round(cnt_expect));
        otherwise
            error("Unsupported cntstat_noise_mode: %s", cntstat_noise_mode);
    end

    CntStat(id_rotate, :) = single(cnt_expect);
end

%% Save outputs
cntstat_csv_path = fullfile(cntstat_dir, sprintf("CntStat_%s_%s.csv", data_file_name, count_level));
writematrix(CntStat, cntstat_csv_path);

info_path = fullfile(cntstat_dir, sprintf("CntStat_%s_%s_info.txt", data_file_name, count_level));
write_summary(info_path, factor_path, energy_keV, rotate_num, total_count, count_level, data_file_name, volume_type, volume_tag, transverse_scale, cntstat_noise_mode, cntstat_csv_path, img_cartesian, img_polar, CntStat);

if save_img_cartesian
    fid = fopen(fullfile(cntstat_dir, sprintf("ImgCartesian_%s_%s.raw", data_file_name, count_level)), "w");
    fwrite(fid, single(img_cartesian), "float32");
    fclose(fid);
end

if save_img_polar
    fid = fopen(fullfile(cntstat_dir, sprintf("ImgPolar_%s_%s.raw", data_file_name, count_level)), "w");
    fwrite(fid, single(img_polar), "float32");
    fclose(fid);
end

fprintf("Saved CntStat: %s\n", cntstat_csv_path);
fprintf("Total counts written: %.0f\n", sum(CntStat, "all"));


function [img_cartesian, x_mm, y_mm, z_mm, volume_tag] = load_hoffman_volume(volume_type, transverse_scale)
base_dir = "./Geant4Sim/Preview/HoffmanRawCompressed_300x300x60_" + format_scale_tag(transverse_scale);
switch string(volume_type)
    case "target"
        raw_path = fullfile(base_dir, "hoffman_compressed_target_float32.raw");
        dims = [100, 100, 20];
        spacing = [3, 3, 3];
        volume_tag = "HoffmanCompressedTarget_" + format_scale_tag(transverse_scale);
    case "native"
        raw_path = fullfile(base_dir, "hoffman_compressed_native_float32.raw");
        dims = [256, 256, 19];
        spacing = [0.97656, 0.97656, 6.39];
        volume_tag = "HoffmanCompressedNative_" + format_scale_tag(transverse_scale);
    otherwise
        error("Unsupported volume_type: %s", volume_type);
end

fid = fopen(raw_path, "r", "ieee-le");
if fid < 0
    error("Failed to open %s", raw_path);
end
img_cartesian = fread(fid, prod(dims), "float32=>single");
fclose(fid);
if numel(img_cartesian) ~= prod(dims)
    error("Unexpected data length in %s", raw_path);
end
img_cartesian = reshape(img_cartesian, dims);

x_mm = voxel_centers(dims(1), spacing(1));
y_mm = voxel_centers(dims(2), spacing(2));
z_mm = voxel_centers(dims(3), spacing(3));

if string(volume_type) == "native"
    x_mm = x_mm * transverse_scale;
    y_mm = y_mm * transverse_scale;
end
end


function centers = voxel_centers(num_voxel, voxel_size)
centers = (-num_voxel / 2 + 0.5) * voxel_size : voxel_size : (num_voxel / 2 - 0.5) * voxel_size;
end


function write_summary(info_path, factor_path, energy_keV, rotate_num, total_count, count_level, data_file_name, volume_type, volume_tag, transverse_scale, noise_mode, cntstat_csv_path, img_cartesian, img_polar, CntStat)
fid = fopen(info_path, "w");
if fid < 0
    error("Failed to open %s for writing.", info_path);
end
fprintf(fid, "GenProj_Hoffman_SPECT_PolarCoor\n");
fprintf(fid, "factor_path = %s\n", factor_path);
fprintf(fid, "energy_keV = %d\n", energy_keV);
fprintf(fid, "rotate_num = %d\n", rotate_num);
fprintf(fid, "total_count = %.8e\n", total_count);
fprintf(fid, "count_level = %s\n", count_level);
fprintf(fid, "data_file_name = %s\n", data_file_name);
fprintf(fid, "volume_type = %s\n", volume_type);
fprintf(fid, "volume_tag = %s\n", volume_tag);
fprintf(fid, "transverse_scale = %.4f\n", transverse_scale);
fprintf(fid, "noise_mode = %s\n", noise_mode);
fprintf(fid, "cntstat_csv_path = %s\n", cntstat_csv_path);
fprintf(fid, "img_cartesian_size = %d x %d x %d\n", size(img_cartesian, 1), size(img_cartesian, 2), size(img_cartesian, 3));
fprintf(fid, "img_polar_size = %d x %d\n", size(img_polar, 1), size(img_polar, 2));
fprintf(fid, "cntstat_size = %d x %d\n", size(CntStat, 1), size(CntStat, 2));
fprintf(fid, "cntstat_total = %.0f\n", sum(CntStat, "all"));
fprintf(fid, "cntstat_single_view_mean = %.4f\n", mean(sum(CntStat, 2)));
fclose(fid);
end


function tag = format_scale_tag(scale_value)
tag = sprintf("XYx%.2f", scale_value);
tag = strrep(tag, ".", "p");
end
