/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 96.3675 -277.9330 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 76.4771 -275.8425 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 84.6118 -294.1134 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 56.5866 -273.7519 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 64.7214 -292.0228 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 72.8561 -310.2937 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 36.6962 -271.6613 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 44.8309 -289.9323 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 52.9657 -308.2032 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 61.1004 -326.4741 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 43.5472 -225.6115 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 60.0052 -202.9590 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 71.3938 -228.5383 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 76.4632 -180.3066 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 87.8518 -205.8858 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 99.2405 -231.4651 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 46.3376 -148.5305 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 10.5349 -144.7675 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 25.1774 -177.6551 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -25.2679 -141.0045 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -10.6254 -173.8921 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 4.0171 -206.7797 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -87.9285 -208.3097 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -62.0660 -172.7129 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -44.1696 -212.9089 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -45.6570 -265.3278 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -97.3721 -259.8923 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -76.2218 -307.3967 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -40.0084 -338.6515 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -4.7413 -290.1105 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 19.6629 -344.9232 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/run/beamOn 83333333
