/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -42.8258 -337.3972 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -38.6676 -317.8342 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -57.6887 -324.0145 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -34.5093 -298.2712 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -53.5304 -304.4516 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -72.5516 -310.6319 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -30.3511 -278.7083 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -49.3722 -284.8886 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -68.3933 -291.0690 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -87.4145 -297.2493 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 14.7303 -290.3353 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 35.5384 -309.0710 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 8.9088 -317.7235 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 56.3465 -327.8066 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 29.7169 -336.4591 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 3.0873 -345.1116 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 91.0974 -301.1676 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 98.5822 -265.9543 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 64.3442 -277.0789 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 106.0670 -230.7410 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 71.8290 -241.8656 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 37.5910 -252.9902 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 45.6804 -161.3883 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 78.3787 -190.8301 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 36.5322 -204.4268 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -15.4440 -197.4683 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -4.6326 -146.6046 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -54.0875 -162.6735 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -88.9565 -195.4215 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -44.3678 -235.5693 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -101.4312 -254.1104 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/run/beamOn 83333333
