/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -99.9232 -264.6629 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -81.6523 -256.5282 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -97.8327 -244.7725 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -63.3814 -248.3934 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -79.5618 -236.6377 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -95.7421 -224.8820 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -45.1105 -240.2587 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -61.2908 -228.5030 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -77.4712 -216.7473 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -93.6515 -204.9916 0.0000 mm
/gps/pos/radius 5.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -28.0188 -283.5645 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -30.9456 -311.4111 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -53.5980 -294.9532 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -33.8724 -339.2578 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -56.5248 -322.7998 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 1.960000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -79.1773 -306.3418 0.0000 mm
/gps/pos/radius 7.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 8.1052 -351.7138 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 40.9928 -337.0713 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 11.8682 -315.9111 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 73.8804 -322.4288 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 44.7558 -301.2685 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 3.240000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 15.6312 -280.1083 0.0000 mm
/gps/pos/radius 9.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 94.4935 -232.8105 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 89.8943 -276.5694 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 4.840000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 54.2975 -250.7069 0.0000 mm
/gps/pos/radius 11.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 29.3762 -204.5671 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 76.8806 -183.4168 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 6.760000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre 34.8117 -152.8520 0.0000 mm
/gps/pos/radius 13.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -12.1775 -143.8912 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -18.4492 -203.5625 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/gps/source/add 9.000000
/gps/particle gamma
/gps/energy 511 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/ang/type iso
/gps/ang/mintheta 0.0000 deg
/gps/ang/maxtheta 180.0000 deg
/gps/pos/centre -66.9902 -168.2954 0.0000 mm
/gps/pos/radius 15.0000 mm
/gps/pos/halfz 15.0000 mm

#
/run/beamOn 83333333
