function results = run_gen_jscc_production_factors()
%RUN_GEN_JSCC_PRODUCTION_FACTORS Build the three long-term JSCC Factors.
% Inputs are the V4-S PE/scatter runs. Outputs use center-inclusive polar
% sampling, the validated absolute layer calibration, and an activity-density
% basis B=A*diag(DeltaV_mm3). Standard no-suffix Factors are replaced only
% after each staged output passes validation.

    grid = struct( ...
        'include_center_point', true, ...
        'apply_polar_volume_weighting', true, ...
        'write_cartesian_tmp', false, ...
        'run_name_suffix', '_pe_v4', ...
        'calibration_profile', 'pe_v4_uniform_fov_layer_20260718');
    results = run_gen_response_factors( ...
        ["JSCC/A218", "JSCC/A440", "JSCC/C440to218"], "", grid);
end
