/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/vis/open OGL 1200x800
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 75 25 deg
/vis/viewer/zoom 2.5
/vis/scene/add/axes 0 -75 0 100 mm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/scene/endOfEventAction accumulate 20
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
